/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class cn_com_reformer_communication_security_SecretKeyKeeper */

#ifndef _Included_cn_com_reformer_communication_security_SecretKeyKeeper
#define _Included_cn_com_reformer_communication_security_SecretKeyKeeper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_com_reformer_communication_security_SecretKeyKeeper
 * Method:    getSECRETKEYC
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_com_reformer_communication_security_SecretKeyKeeper_getSECRETKEYC
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     cn_com_reformer_communication_security_SecretKeyKeeper
 * Method:    rollSecretKeyC
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_cn_com_reformer_communication_security_SecretKeyKeeper_rollSecretKeyC
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     cn_com_reformer_communication_security_SecretKeyKeeper
 * Method:    syncSecretKeyC
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_cn_com_reformer_communication_security_SecretKeyKeeper_syncSecretKeyC
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     cn_com_reformer_communication_security_SecretKeyKeeper
 * Method:    getDEVICE_ORIGINAL_SECRETKEYS
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_com_reformer_communication_security_SecretKeyKeeper_getDEVICE_1ORIGINAL_1SECRETKEYSC
  (JNIEnv *, jclass);

/*
 * Class:     cn_com_reformer_communication_security_SecretKeyKeeper
 * Method:    getSERVER_ORIGINAL_SECRETKEYS
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_com_reformer_communication_security_SecretKeyKeeper_getSERVER_1ORIGINAL_1SECRETKEYSC
  (JNIEnv *, jclass);

/*
 * Class:     cn_com_reformer_communication_security_SecretKeyKeeper
 * Method:    getCONFIG_ORIGINAL_SECRETKEYS
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_com_reformer_communication_security_SecretKeyKeeper_getCONFIG_1ORIGINAL_1SECRETKEYSC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
