/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class cn_com_reformer_license_util_SysInfo */

#ifndef _Included_cn_com_reformer_license_util_SysInfo
#define _Included_cn_com_reformer_license_util_SysInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_com_reformer_license_util_SysInfo
 * Method:    getmid
 * Signature: ()Ljava/lang/String;
 * function:  ∂¡»°MAC
 */
JNIEXPORT jstring JNICALL Java_cn_com_reformer_license_util_SysInfo_getmid
  (JNIEnv *, jobject);

/*
 * Class:     cn_com_reformer_license_util_SysInfo
 * Method:    getcid
 * Signature: ()Ljava/lang/String;
 * function:  ∂¡»°CPUŒ®“ªID
 */
JNIEXPORT jstring JNICALL Java_cn_com_reformer_license_util_SysInfo_getcid
  (JNIEnv *, jobject);

/*
 * Class:     cn_com_reformer_license_util_SysInfo
 * Method:    getdid
 * Signature: ()Ljava/lang/String;
 * function:  ∂¡»°”≤≈Ã–Ú¡–∫≈
 */
JNIEXPORT jstring JNICALL Java_cn_com_reformer_license_util_SysInfo_getdid
  (JNIEnv *, jobject);

/*
 * Class:     cn_com_reformer_license_util_SysInfo
 * Method:    getbid
 * Signature: ()Ljava/lang/String;
 * function:  ∂¡»°BIOS±‡∫≈
 */
JNIEXPORT jstring JNICALL Java_cn_com_reformer_license_util_SysInfo_getbid
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
